spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.dao.entity
  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: Y
      logic-not-delete-value: N
  # 映射规则
  configuration:
    map-underscore-to-camel-case: true
  # 是否开启二级缓存
    cache-enabled: false
  # select结果为空，key值为null
    call-setters-on-nulls: true
logging:
  level:
    com.demo.dao.mapper: debug